main: br.com.pepe.GunthMC.Main
version: 1.2.2
name: Gt-General
commands:
   GunthMC:
      aliases: [gt, gunthmcv2, comandos, ajuda]
   PluginInfo:
      aliases: [plinfo, infopl, pl, plugin, gtmcpl]
